name: Build Flatpak

on:
  # Enable manual run
  workflow_dispatch:
  pull_request:

env:
  project-id: codes.merritt.FeelingFinder

jobs:
  build-flatpak:
    name: Build .flatpak artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: beta

      - name: Build Flutter linux version
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux

      - name: Compress Flutter build
        run: tar -C build/linux/x64/release/bundle -cvf FlutterApp-Linux-Portable.tar.gz .

      - name: Upload app archive for next steps
        uses: actions/upload-artifact@v2
        with:
          name: FlutterApp-Archive
          path: FlutterApp-Linux-Portable.tar.gz

  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08
      options: --privileged
    steps:
      - name: Download app archive
        uses: actions/download-artifact@v3
        with:
          name: FlutterApp-Archive

      - name: Build .flatpak
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: FlutterApp.flatpak
          manifest-path: com.example.FlutterApp.json

      - name: Upload .flatpak artifact to workflow
        uses: actions/upload-artifact@v2
        with:
          path: FlutterApp.flatpak
